<?php
//print_r($result);exit;
$rows=array();
/*$servername = "localhost";
$username = "root";
$password = "";
$dbname = "drivingschool";*/
$servername = "localhost";
$username = "valleydr_valley2";
$password = "hT8Wru5VD2";
$dbname = "valleydr_driving";
$today = date('Y-m-d');

//Delay BEFORE payment is due
$delay_days = 14;
//Delay AFTER payment is late
$late_days = 300;

$noticedate = date('Y-m-d', strtotime( "$today + $delay_days days" ));
$latedate = date('Y-m-d', strtotime( "$today - $late_days days" ));

$conn = new mysqli($servername, $username, $password, $dbname);
$query = "SELECT st.StudentID ,Phone,ClassStart,FirstName,LastName,StudentEmail,ifNull(sum(cl.Hours),0) AS totalhrs FROM `student_information` as st left join `car_log` as cl on st.StudentID=cl.StudentID WHERE   STR_TO_DATE(InCarStart, '%d/%m/%Y') <= DATE(NOW() - INTERVAL 300 DAY)   GROUP BY st.StudentID having ifNull(sum(cl.Hours),0) < 10
ORDER BY `st`.`StudentEmail`  DESC";
$loopquery=$conn->query($query);
 $rowcount=mysqli_num_rows($loopquery); 
 if($rowcount>0){
	 $messagetable = "<table width=100% border=0 cellspacing=1 cellpadding=3 bgcolor=#C0C0C0 style='margin-left:auto;margin-right:auto;'>
            
                <tr>
                    <th scope='col' bgcolor=#EFEFEF align=center ><b>Name</b></th>                
                    <th scope='col' bgcolor=#F6F6F6 align=center>Course Type</th>
					<th scope='col' bgcolor=#F6F6F6 align=center>Phone</th>
					<th scope='col' bgcolor=#F6F6F6 align=center>Email</th>
                    <th scope='col' bgcolor=#F6F6F6 align=center>Remaining Hours</th>
                    <th scope='col' bgcolor=#F6F6F6 align=center>Status</th>
                </tr>"; 	 
while($result=$loopquery->fetch_assoc()){ 
		//print_r($result); exit;
		$carhour = (10 - $result['totalhrs']);
		$messagetable .= "<tr>
                        <td bgcolor=#FFFFFF align=Center>" . $result['LastName']." ".$result['FirstName']  . "</td>
						<td bgcolor=#FFFFFF align=Center>Car</td>
						<td bgcolor=#FFFFFF align=Center>".$result['Phone']."</td>
						<td bgcolor=#FFFFFF align=Center>".$result['StudentEmail']."</td>
                        <td bgcolor=#FFFFFF align=Center>" . $carhour . "</td>
                        <td bgcolor=#FFFFFF align=Center>Due</td>
                    </tr>\r";
}

         $messagetable .= "</table>";
		$SiteTitle = "Driving School Management System  ";
		$SiteEmail = "afzal@navigatormarketing.ca";
		$SiteURL   = "http://valleydriver.ca/valleydrivingap"; 
		
		$todays_date = date('l, F d, Y', strtotime($today));
		$mail_subject = $SiteTitle . " - Car Course Duration Running Out";
		$noticetype = "Car Course duration running out";
		$message = "  <br/>
					  10 month alert:  These students have not completed their requirements as of this date.\r\n <br/>
					  List names:\r\n <br/><br/>
					  ";
		$message .= $messagetable; 
		$message .= "<p>Thanks,<br>
					  Alert email generated by System</p>\r";
		$messageBottom = "Thank you<br />" . $SiteTitle;
		$mailmsg ="";
		$mailmsg .= "<h2 style='text-align: center'>" . $noticetype . "</h2>";
		$mailmsg .= "<p><span style='float:right;padding-right:30px;'>" . $todays_date . "</span>Hi Administrator,</p>"; 
		$mailmsg .= "<p>" . $message . "</p>\r";
		
		$mailmsg .= "<p>" . $messageBottom . "</p>\r"; 
		
		$mail_body = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">
            <html>
                <head>
                <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />
                </head>
                <body>
                    <center>
                        <table width=98% border=\"0\" align=\"center\" cellpadding=1 cellspacing=\"0\" >
                            <tr>
                                <td align=\"center\" valign=\"top\">
                                    <table width=900px border=\"0\"  cellpadding=\"0\" cellspacing=\"0\" style='border:2px solid; border-color:#969696'>
                                        <tr>                                            
                                            <td bgcolor=\"#FFFFFF\" align=\"left\" style=\"padding:14px;\">" . $mailmsg . "</td>                                            
                                        </tr>
                                        <tr>
                                            <td bgcolor=#606060 align=\"center\" style=\"padding:2px; border-top:2px solid; border-color:#777777\">
                                                <a href=\"" . $SiteURL . "\" style='color:#ffffff; text-decoration:none'>" . $SiteTitle . "</a>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </center>
                </body>
            </html>";
		
		
		$mail_to = 'afzal@navigatormarketing.ca';//$result['StudentEmail'];
		$headers = "From: \"$SiteTitle\" <$SiteEmail>\r\n";
		$headers .= "Reply-To: $SiteEmail\r\n";
		$headers .= "Organization: $SiteTitle \r\n";
		$headers .= "X-Sender: $SiteEmail \r\n";
		$headers .= "X-Priority: 3 \r\n";
		$headers .= "X-Mailer: php\r\n";
		$headers .= "MIME-Version: 1.0\r\n";
		$headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";
		@mail($mail_to, $mail_subject, $mail_body, $headers); 
//echo $mail_body; 

}

$query = "SELECT st.StudentID ,ClassStart,Phone,FirstName,LastName,StudentEmail,ifNull(sum(cl.Hours),0) AS totalhrs FROM `student_information` as st left join `class_log` as cl on st.StudentID=cl.StudentID WHERE   STR_TO_DATE(ClassStart, '%d/%m/%Y') <= DATE(NOW() - INTERVAL 300 DAY)   GROUP BY st.StudentID having ifNull(sum(cl.Hours),0) < 20
ORDER BY `st`.`StudentEmail`  DESC";
$loopquery=$conn->query($query);
 $rowcount=mysqli_num_rows($loopquery); 
 if($rowcount>0){
	 $messagetable = "<table width=100% border=0 cellspacing=1 cellpadding=3 bgcolor=#C0C0C0 style='margin-left:auto;margin-right:auto;'>
             <tr>
                    <th scope='col' bgcolor=#EFEFEF align=center ><b>Name</b></th>                
                    <th scope='col' bgcolor=#F6F6F6 align=center>Course Type</th>
					<th scope='col' bgcolor=#F6F6F6 align=center>Phone</th>
					<th scope='col' bgcolor=#F6F6F6 align=center>Email</th>
                    <th scope='col' bgcolor=#F6F6F6 align=center>Remaining Hours</th>
                    <th scope='col' bgcolor=#F6F6F6 align=center>Status</th>
                </tr>"; 	 
while($result=$loopquery->fetch_assoc()){ 
		//print_r($result); exit;
		$carhour = (20 - $result['totalhrs']);
		$messagetable .= "<tr>
                        <td bgcolor=#FFFFFF align=Center>" . $result['LastName']." ".$result['FirstName']  . "</td>
						<td bgcolor=#FFFFFF align=Center>Class</td>
						<td bgcolor=#FFFFFF align=Center>".$result['Phone']."</td>
						<td bgcolor=#FFFFFF align=Center>".$result['StudentEmail']."</td>
                        <td bgcolor=#FFFFFF align=Center>" . $carhour . "</td>
                        <td bgcolor=#FFFFFF align=Center>Due</td>
                    </tr>\r";
}

         $messagetable .= "</table>";
		$SiteTitle = "Driving School Management System ";
		$SiteEmail = "afzal@navigatormarketing.ca";
		$SiteURL   = "http://valleydriver.ca/valleydrivingap"; 
		
		$todays_date = date('l, F d, Y', strtotime($today));
		$mail_subject = $SiteTitle . " - Class Course Duration Running Out";
		$noticetype = "Class Course duration running out";
		$message = " \r \n <br/>
10 month alert:  These students have not completed their requirements as of this date.\r\n <br/>
List names:\r\n <br/><br/>
";
$message .= $messagetable; 
		$message .= "<p>Thanks,<br>
Alert email generated by System</p>\r";
		$messageBottom = "Thank you<br />" . $SiteTitle;
		$mailmsg ="";
		$mailmsg .= "<h2 style='text-align: center'>" . $noticetype . "</h2>";
		$mailmsg .= "<p><span style='float:right;padding-right:30px;'>" . $todays_date . "</span>Hi Administrator,</p>"; 
		$mailmsg .= "<p>" . $message . "</p>\r";
		
		$mailmsg .= "<p>" . $messageBottom . "</p>\r"; 
		
		$mail_body = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">
            <html>
                <head>
                <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />
                </head>
                <body>
                    <center>
                        <table width=98% border=\"0\" align=\"center\" cellpadding=1 cellspacing=\"0\" >
                            <tr>
                                <td align=\"center\" valign=\"top\">
                                    <table width=900px border=\"0\"  cellpadding=\"0\" cellspacing=\"0\" style='border:2px solid; border-color:#969696'>
                                        <tr>                                            
                                            <td bgcolor=\"#FFFFFF\" align=\"left\" style=\"padding:14px;\">" . $mailmsg . "</td>                                            
                                        </tr>
                                        <tr>
                                            <td bgcolor=#606060 align=\"center\" style=\"padding:2px; border-top:2px solid; border-color:#777777\">
                                                <a href=\"" . $SiteURL . "\" style='color:#ffffff; text-decoration:none'>" . $SiteTitle . "</a>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </center>
                </body>
            </html>";
		
		
		$mail_to = 'afzal@navigatormarketing.ca';//$result['StudentEmail'];
		$headers = "From: \"$SiteTitle\" <$SiteEmail>\r\n";
		$headers .= "Reply-To: $SiteEmail\r\n";
		$headers .= "Organization: $SiteTitle \r\n";
		$headers .= "X-Sender: $SiteEmail \r\n";
		$headers .= "X-Priority: 3 \r\n";
		$headers .= "X-Mailer: php\r\n";
		$headers .= "MIME-Version: 1.0\r\n";
		$headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";
		@mail($mail_to, $mail_subject, $mail_body, $headers); 
//echo $mail_body; 

}




?>
<!--?userid=50&password=546872Whsgf67hGfzs-->